In [1]:
## BOW,TFIDF,MAchine Learning Algorithms

In [2]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
## Data Cleaning And Preprocessing
import re 
import nltk
nltk.download('stopwords')

C:\Users\shrey\anaconda3\lib\site-packages\scipy\__init__.py:173: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.19.2)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shrey\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [6]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word  in stopwords.words('english')]
    review= ' '.join(review)
    corpus.append(review)

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

###  BOW 

In [8]:
## Output Features

y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values   # We can pick either of the column so we have taken only 1 column ham

In [9]:
## Train test split 

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2)

In [10]:
# Create the bag of words model

from sklearn.feature_extraction.text import CountVectorizer

# For binary BOW enable binary = True

cv=CountVectorizer(max_features=3000,ngram_range=(1, 2))

In [11]:
x_train

['still come tonight',
 'feel like tri kadeem v',
 'yeah prob last night obvious catch speak soon',
 'guarante award even cashto claim ur award call free stop getstop php rg jx',
 'cant pick phone right pl send messag',
 'part initi understand',
 'im gloucesterroad uup later',
 'slept thinkthi time lt gt pm danger',
 'msg rajini come',
 'urgent nd attempt contact u prize yesterday still await collect claim call acl pm',
 'promot number ur award citi break could win summer shop spree everi wk txt store skilgm tsc winawk age perwksub',
 'costa del sol holiday await collect call toclaim sae tc pobox stockport sk xh cost pm max min',
 'norm tomorrow finish co st test need sort librari stuff point tomo got letter today access til end march better get move',
 'thnx dude u guy nite',
 'sorri call later meet',
 'still west coast haiz take forev come back',
 'wat time r go xin hostel',
 'sorri meet call later',
 'yo gonna still stock tomorrow today tri get dubsack',
 'ya knw u vl giv ok thank k

In [12]:
## Independent Features

x_train=cv.fit_transform(x_train).toarray()

In [13]:
x_train    # Converted sentences into vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
len(x_train),len(y_train)

(4457, 4457)

In [15]:
x_test   # X-test is a sentence and we need to convert this into vectors

['dont want hear anyth',
 'town ju take mrt later',
 'sure night menu know noon menu',
 'en chikku nang bakra msg kalstiya tea coffe',
 'big chic common declar',
 'hi hope ur day good back walk tabl book half eight let know ur come',
 'ye tv alway avail work place',
 'huh cant go ur hous empti hand right',
 'thanx today cer nice catch ave find time often oh well take care c u soon c',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',
 'movi collect car oredi',
 'think chennai forgot come auction',
 'happi birthday may ur dream come true',
 'oki scare u say fat u dun wan alreadi',
 'want explicit sex sec ring cost p min',
 'hello per request lt gt rs transfer',
 'oh ya ya rememb da',
 'yet like keep touch easiest way barcelona way ru hous',
 'u lost ill alway b u intend hurt u never knew u felt iwa marin itri tell urmom careabout u',
 'go open room til thanksgiv without upcharg',
 'shit babe thasa bit mess yeh shudvetold u urgran know neway ills

In [16]:
x_test=cv.transform(x_test).toarray()   # We are not fitting the data into the model, simply transforming it as using fit it is going to learn from the data.

In [17]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
x_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [19]:
cv.vocabulary_

{'still': 2358,
 'come': 457,
 'tonight': 2599,
 'feel': 808,
 'like': 1398,
 'tri': 2617,
 'kadeem': 1289,
 'feel like': 810,
 'yeah': 2972,
 'prob': 1983,
 'last': 1336,
 'night': 1726,
 'obvious': 1759,
 'catch': 356,
 'speak': 2326,
 'soon': 2315,
 'last night': 1337,
 'speak soon': 2328,
 'guarante': 1043,
 'award': 148,
 'even': 754,
 'claim': 408,
 'ur': 2703,
 'call': 271,
 'free': 855,
 'stop': 2366,
 'guarante award': 1044,
 'claim ur': 415,
 'ur award': 2705,
 'award call': 150,
 'call free': 282,
 'cant': 334,
 'pick': 1875,
 'phone': 1867,
 'right': 2090,
 'pl': 1886,
 'send': 2188,
 'messag': 1544,
 'cant pick': 336,
 'pick phone': 1877,
 'phone right': 1871,
 'right pl': 2091,
 'pl send': 1896,
 'send messag': 2192,
 'part': 1836,
 'understand': 2683,
 'im': 1207,
 'later': 1342,
 'slept': 2284,
 'time': 2545,
 'lt': 1470,
 'gt': 1025,
 'pm': 1921,
 'lt gt': 1472,
 'msg': 1633,
 'urgent': 2728,
 'nd': 1683,
 'attempt': 135,
 'contact': 486,
 'prize': 1976,
 'yesterday': 

In [20]:
## Use of Machine learning algorithm

from sklearn.naive_bayes import MultinomialNB   # NB is used as it is very good in handling the sparse matrix

In [21]:
spam_detect_model=MultinomialNB().fit(x_train,y_train)

In [22]:
y_pred=spam_detect_model.predict(x_test)

In [23]:
## Comparision of y_test and y_pred

from sklearn.metrics import accuracy_score,classification_report

In [24]:
score=accuracy_score(y_test,y_pred)
score

0.9865470852017937

In [25]:
CR=classification_report(y_test,y_pred)
print(CR)

              precision    recall  f1-score   support

           0       0.98      0.90      0.94       131
           1       0.99      1.00      0.99       984

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



### Creating the TFIDF model

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_rain,y_test=train_test_split(corpus,y,test_size=0.2)

In [35]:
y=messages['label']

In [36]:
y=pd.get_dummies(y)

In [37]:
y=y.iloc[:,0]

In [38]:
y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: ham, Length: 5572, dtype: uint8

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [42]:
x_train=tv.fit_transform(x_train).toarray()
x_test=tv.transform(x_test).toarray()

In [43]:
tv.vocabulary_

{'download': 567,
 'app': 82,
 'good': 832,
 'need': 1411,
 'drug': 576,
 'keep': 1070,
 'pix': 1581,
 'cum': 461,
 'thank': 2093,
 'hope': 962,
 'enjoy': 613,
 'game': 764,
 'yesterday': 2489,
 'sorri': 1933,
 'touch': 2167,
 'pl': 1583,
 'know': 1087,
 'great': 858,
 'week': 2366,
 'abiola': 2,
 'hope enjoy': 963,
 'yup': 2498,
 'comin': 393,
 'date': 488,
 'freemsg': 742,
 'record': 1710,
 'may': 1276,
 'entitl': 618,
 'pound': 1625,
 'accid': 9,
 'claim': 350,
 'free': 728,
 'repli': 1729,
 'ye': 2478,
 'msg': 1375,
 'opt': 1512,
 'text': 2080,
 'stop': 1988,
 'free repli': 739,
 'repli ye': 1733,
 'text stop': 2086,
 'mobil': 1335,
 'mth': 1380,
 'updat': 2241,
 'latest': 1116,
 'colour': 381,
 'camera': 283,
 'call': 250,
 'mobil mth': 1341,
 'updat latest': 2242,
 'latest colour': 1118,
 'colour camera': 382,
 'camera mobil': 285,
 'mobil free': 1340,
 'free call': 731,
 'call mobil': 265,
 'see': 1814,
 'cup': 462,
 'coffe': 372,
 'convey': 423,
 'birthday': 173,
 'wish': 2412,

In [47]:
## Use of machine learning algorithm

from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB().fit(x_train,y_train)

In [48]:
## Prediction

y_pred=nb.predict(x_test)

In [49]:
## Accuracy score

from sklearn.metrics import accuracy_score,classification_report

score=accuracy_score(y_test,y_pred)
print(score)

0.8556053811659193


In [50]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.01      0.02       163
           1       0.86      1.00      0.92       952

    accuracy                           0.86      1115
   macro avg       0.93      0.51      0.47      1115
weighted avg       0.88      0.86      0.79      1115



##  Best Practices for solving above probelms

1) Data Cleaning and Preprocessing

2) Train test split.

3) BOW and TFIDF  implementation  (Converted Sentences into Vectors) (This step should be performed to prevent data leakage)

4) Model accuracy 