## Working on google pretrained model

In [1]:
!pip install gensim

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

scipy 1.10.1 requires numpy<1.27.0,>=1.19.5, but you'll have numpy 1.19.2 which is incompatible.


  Attempting uninstall: scipy
    Found existing installation: scipy 1.5.2
    Uninstalling scipy-1.5.2:
      Successfully uninstalled scipy-1.5.2


In [2]:
import gensim

C:\Users\shrey\anaconda3\lib\site-packages\scipy\__init__.py:173: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 1.19.2)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
from gensim.models import word2vec, KeyedVectors

In [ ]:
## References: https://stackoverflow.com/questions/46433778/import-googlenews-vectors-negative300-bin

In [6]:
import gensim.downloader as api

In [7]:
vec=api.load('word2vec-google-news-300')   ## Load the google pretrained library

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [8]:
vec_king=vec['king']

In [9]:
vec_king    # Vector representation of the word king having 300 rows

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [10]:
vec_king.shape

(300,)

In [11]:
vec['hungry']

array([ 4.39453125e-02,  3.51562500e-01, -2.05078125e-01,  1.78710938e-01,
       -2.08984375e-01,  1.39648438e-01,  1.40625000e-01, -2.25585938e-01,
       -2.43164062e-01,  2.73437500e-01, -4.46777344e-02,  1.97265625e-01,
        6.59179688e-02,  1.15234375e-01,  1.51367188e-02, -1.31835938e-01,
       -1.98242188e-01,  5.49316406e-02,  1.97265625e-01,  9.96093750e-02,
        6.49414062e-02,  3.66210938e-02,  2.35351562e-01,  1.17187500e-01,
        9.13085938e-02, -6.78710938e-02, -1.49414062e-01, -1.78222656e-02,
        1.35742188e-01, -1.75781250e-01,  4.08935547e-03,  2.36328125e-01,
       -4.68750000e-02, -1.21582031e-01,  3.14941406e-02,  5.27343750e-02,
       -3.30078125e-01,  6.73828125e-02,  9.81445312e-02,  4.96093750e-01,
        1.05468750e-01, -1.40625000e-01,  1.88476562e-01,  1.86523438e-01,
        2.59765625e-01, -9.86328125e-02, -2.06054688e-01,  2.57812500e-01,
       -7.32421875e-02,  2.30468750e-01, -1.64062500e-01,  3.78417969e-02,
       -1.43554688e-01,  

In [13]:
vec.most_similar('hungry')

[('famished', 0.6286771893501282),
 ('starving', 0.6246457099914551),
 ('thirsty', 0.6115206480026245),
 ('Hungry', 0.6091951131820679),
 ('ravenous', 0.5776185989379883),
 ('babies_wailed', 0.5719088315963745),
 ('Felicie_Colin', 0.5705069899559021),
 ('ginger_haired_perpetually', 0.5697963237762451),
 ('starved', 0.559722363948822),
 ('miner_Jerry_Lepolese', 0.5590986609458923)]

In [17]:
vec.most_similar('Basketball')

[('Volleyball', 0.6832056641578674),
 ('Football', 0.6591217517852783),
 ('Baskeball', 0.6529102325439453),
 ('basketball', 0.6480608582496643),
 ('Soccer', 0.6463675498962402),
 ('Softball', 0.6330848932266235),
 ('Baseball', 0.6273959279060364),
 ('Women_Basketball', 0.6263864040374756),
 ('Tennis', 0.6097691655158997),
 ('Lacrosse', 0.608349084854126)]

In [18]:
vec.similarity('basketball','cricket')     ## How much the word vectors of basketball and cricket are similar ?

0.36732137

In [19]:
vec1=vec['king']-vec['man']+vec['woman']

In [23]:
vec1

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [22]:
vec.most_similar(vec1)

[('king', 0.8449392318725586),
 ('queen', 0.7300518155097961),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676948547363),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613664388656616),
 ('sultan', 0.5376776456832886),
 ('Queen_Consort', 0.5344247221946716),
 ('queens', 0.5289887189865112)]